// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * BookmarkConflictItem describes an incoming bookmark that looks like an update.
 */
export class BookmarkConflictItem {
    /**
     * Creates a new BookmarkConflictItem instance.
     * @param {Partial<BookmarkConflictItem>} [$$source = {}] - The source object to create the BookmarkConflictItem.
     */
    constructor($$source = {}) {
        if (!("folderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderPath"] = "";
        }
        if (!("existingTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["existingTitle"] = "";
        }
        if (!("incomingTitle" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["incomingTitle"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("existingMeta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["existingMeta"] = "";
        }
        if (!("incomingMeta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["incomingMeta"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkConflictItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BookmarkConflictItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BookmarkConflictItem(/** @type {Partial<BookmarkConflictItem>} */($$parsedSource));
    }
}

/**
 * BookmarkIndexEntry holds a flattened bookmark for search indexing.
 */
export class BookmarkIndexEntry {
    /**
     * Creates a new BookmarkIndexEntry instance.
     * @param {Partial<BookmarkIndexEntry>} [$$source = {}] - The source object to create the BookmarkIndexEntry.
     */
    constructor($$source = {}) {
        if (!("nodeId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["nodeId"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("folderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderPath"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkIndexEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BookmarkIndexEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BookmarkIndexEntry(/** @type {Partial<BookmarkIndexEntry>} */($$parsedSource));
    }
}

/**
 * BookmarkMergeItem describes a bookmark involved in a merge report.
 */
export class BookmarkMergeItem {
    /**
     * Creates a new BookmarkMergeItem instance.
     * @param {Partial<BookmarkMergeItem>} [$$source = {}] - The source object to create the BookmarkMergeItem.
     */
    constructor($$source = {}) {
        if (!("folderPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["folderPath"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkMergeItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BookmarkMergeItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BookmarkMergeItem(/** @type {Partial<BookmarkMergeItem>} */($$parsedSource));
    }
}

/**
 * FlatNodeDTO is a flat representation of a single node.
 * Used for efficient serialization of large trees -- no nested objects,
 * parentId references replace the tree hierarchy.
 */
export class FlatNode {
    /**
     * Creates a new FlatNode instance.
     * @param {Partial<FlatNode>} [$$source = {}] - The source object to create the FlatNode.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {NodeType}
             */
            this["type"] = NodeType.$zero;
        }
        if (!("parentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["parentId"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("iconURI" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconURI"] = "";
        }
        if (!("addDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["addDate"] = "";
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastModified"] = "";
        }
        if (!("meta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["meta"] = "";
        }
        if (!("childCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["childCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FlatNode instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FlatNode}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FlatNode(/** @type {Partial<FlatNode>} */($$parsedSource));
    }
}

/**
 * FolderMergeItem describes a folder that would be created.
 */
export class FolderMergeItem {
    /**
     * Creates a new FolderMergeItem instance.
     * @param {Partial<FolderMergeItem>} [$$source = {}] - The source object to create the FolderMergeItem.
     */
    constructor($$source = {}) {
        if (!("path" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["path"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderMergeItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderMergeItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FolderMergeItem(/** @type {Partial<FolderMergeItem>} */($$parsedSource));
    }
}

/**
 * HistoryState reports whether undo/redo is currently available.
 */
export class HistoryState {
    /**
     * Creates a new HistoryState instance.
     * @param {Partial<HistoryState>} [$$source = {}] - The source object to create the HistoryState.
     */
    constructor($$source = {}) {
        if (!("canUndo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canUndo"] = false;
        }
        if (!("canRedo" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["canRedo"] = false;
        }
        if (!("undoLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["undoLabel"] = "";
        }
        if (!("redoLabel" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["redoLabel"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new HistoryState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {HistoryState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new HistoryState(/** @type {Partial<HistoryState>} */($$parsedSource));
    }
}

/**
 * MergeApplyResult summarizes an applied merge.
 */
export class MergeApplyResult {
    /**
     * Creates a new MergeApplyResult instance.
     * @param {Partial<MergeApplyResult>} [$$source = {}] - The source object to create the MergeApplyResult.
     */
    constructor($$source = {}) {
        if (!("foldersAdded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["foldersAdded"] = 0;
        }
        if (!("bookmarksAdded" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bookmarksAdded"] = 0;
        }
        if (!("duplicatesSkipped" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["duplicatesSkipped"] = 0;
        }
        if (!("potentialUpdates" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["potentialUpdates"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergeApplyResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergeApplyResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new MergeApplyResult(/** @type {Partial<MergeApplyResult>} */($$parsedSource));
    }
}

/**
 * MergePreview summarizes what an import would add or skip.
 */
export class MergePreview {
    /**
     * Creates a new MergePreview instance.
     * @param {Partial<MergePreview>} [$$source = {}] - The source object to create the MergePreview.
     */
    constructor($$source = {}) {
        if (!("foldersToAdd" in $$source)) {
            /**
             * @member
             * @type {FolderMergeItem[]}
             */
            this["foldersToAdd"] = [];
        }
        if (!("bookmarksToAdd" in $$source)) {
            /**
             * @member
             * @type {BookmarkMergeItem[]}
             */
            this["bookmarksToAdd"] = [];
        }
        if (!("duplicateBookmarks" in $$source)) {
            /**
             * @member
             * @type {BookmarkMergeItem[]}
             */
            this["duplicateBookmarks"] = [];
        }
        if (!("potentialUpdates" in $$source)) {
            /**
             * @member
             * @type {BookmarkConflictItem[]}
             */
            this["potentialUpdates"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MergePreview instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MergePreview}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType1;
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType3;
        const $$createField3_0 = $$createType5;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("foldersToAdd" in $$parsedSource) {
            $$parsedSource["foldersToAdd"] = $$createField0_0($$parsedSource["foldersToAdd"]);
        }
        if ("bookmarksToAdd" in $$parsedSource) {
            $$parsedSource["bookmarksToAdd"] = $$createField1_0($$parsedSource["bookmarksToAdd"]);
        }
        if ("duplicateBookmarks" in $$parsedSource) {
            $$parsedSource["duplicateBookmarks"] = $$createField2_0($$parsedSource["duplicateBookmarks"]);
        }
        if ("potentialUpdates" in $$parsedSource) {
            $$parsedSource["potentialUpdates"] = $$createField3_0($$parsedSource["potentialUpdates"]);
        }
        return new MergePreview(/** @type {Partial<MergePreview>} */($$parsedSource));
    }
}

/**
 * NodeType distinguishes folders from bookmarks.
 * @readonly
 * @enum {number}
 */
export const NodeType = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: 0,

    TypeFolder: 0,
    TypeBookmark: 1,
};

// Private type creation functions
const $$createType0 = FolderMergeItem.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = BookmarkMergeItem.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = BookmarkConflictItem.createFrom;
const $$createType5 = $Create.Array($$createType4);
