// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddBookmark(arg1, arg2) {
  return window['go']['wailsapi']['Handler']['AddBookmark'](arg1, arg2);
}

export function AddFolder(arg1, arg2) {
  return window['go']['wailsapi']['Handler']['AddFolder'](arg1, arg2);
}

export function ApplyImportMerge(arg1) {
  return window['go']['wailsapi']['Handler']['ApplyImportMerge'](arg1);
}

export function DeleteNode(arg1) {
  return window['go']['wailsapi']['Handler']['DeleteNode'](arg1);
}

export function DeleteNodes(arg1) {
  return window['go']['wailsapi']['Handler']['DeleteNodes'](arg1);
}

export function FetchFavicon(arg1) {
  return window['go']['wailsapi']['Handler']['FetchFavicon'](arg1);
}

export function FetchFaviconsForNodes(arg1) {
  return window['go']['wailsapi']['Handler']['FetchFaviconsForNodes'](arg1);
}

export function FetchPageTitle(arg1) {
  return window['go']['wailsapi']['Handler']['FetchPageTitle'](arg1);
}

export function FilePath() {
  return window['go']['wailsapi']['Handler']['FilePath']();
}

export function GetAllFolders() {
  return window['go']['wailsapi']['Handler']['GetAllFolders']();
}

export function GetFlatIndex() {
  return window['go']['wailsapi']['Handler']['GetFlatIndex']();
}

export function GetFlatTree() {
  return window['go']['wailsapi']['Handler']['GetFlatTree']();
}

export function GetFolderChildren(arg1) {
  return window['go']['wailsapi']['Handler']['GetFolderChildren'](arg1);
}

export function GetHistoryState() {
  return window['go']['wailsapi']['Handler']['GetHistoryState']();
}

export function GetRootNodes() {
  return window['go']['wailsapi']['Handler']['GetRootNodes']();
}

export function GetTreeStats() {
  return window['go']['wailsapi']['Handler']['GetTreeStats']();
}

export function LoadFile(arg1) {
  return window['go']['wailsapi']['Handler']['LoadFile'](arg1);
}

export function MoveNode(arg1, arg2, arg3) {
  return window['go']['wailsapi']['Handler']['MoveNode'](arg1, arg2, arg3);
}

export function MoveNodes(arg1, arg2) {
  return window['go']['wailsapi']['Handler']['MoveNodes'](arg1, arg2);
}

export function OpenURL(arg1) {
  return window['go']['wailsapi']['Handler']['OpenURL'](arg1);
}

export function PreviewImportMerge(arg1) {
  return window['go']['wailsapi']['Handler']['PreviewImportMerge'](arg1);
}

export function Redo() {
  return window['go']['wailsapi']['Handler']['Redo']();
}

export function Undo() {
  return window['go']['wailsapi']['Handler']['Undo']();
}

export function UpdateBookmark(arg1, arg2) {
  return window['go']['wailsapi']['Handler']['UpdateBookmark'](arg1, arg2);
}

export function UpdateFolderName(arg1, arg2) {
  return window['go']['wailsapi']['Handler']['UpdateFolderName'](arg1, arg2);
}
