// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {wailsapi} from '../models';
import {bookmarks} from '../models';

export function AddBookmark(arg1:string,arg2:wailsapi.BookmarkCreateDTO):Promise<bookmarks.FlatNode>;

export function AddFolder(arg1:string,arg2:string):Promise<bookmarks.FlatNode>;

export function ApplyImportMerge(arg1:string):Promise<bookmarks.MergeApplyResult>;

export function DeleteNode(arg1:string):Promise<void>;

export function DeleteNodes(arg1:Array<string>):Promise<void>;

export function FetchFavicon(arg1:string):Promise<string>;

export function FetchFaviconsForNodes(arg1:Array<string>):Promise<Array<bookmarks.FlatNode>>;

export function FetchPageTitle(arg1:string):Promise<string>;

export function FilePath():Promise<string>;

export function GetAllFolders():Promise<Array<wailsapi.NodeDTO>>;

export function GetFlatIndex():Promise<Array<bookmarks.BookmarkIndexEntry>>;

export function GetFlatTree():Promise<Array<bookmarks.FlatNode>>;

export function GetFolderChildren(arg1:string):Promise<Array<bookmarks.FlatNode>>;

export function GetHistoryState():Promise<bookmarks.HistoryState>;

export function GetRootNodes():Promise<Array<bookmarks.FlatNode>>;

export function LoadFile(arg1:string):Promise<void>;

export function MoveNode(arg1:string,arg2:string,arg3:number):Promise<wailsapi.MoveResult>;

export function MoveNodes(arg1:Array<string>,arg2:string):Promise<wailsapi.MoveResult>;

export function OpenURL(arg1:string):Promise<void>;

export function PreviewImportMerge(arg1:string):Promise<bookmarks.MergePreview>;

export function Redo():Promise<bookmarks.HistoryState>;

export function RefreshTitlesForNodes(arg1:Array<string>):Promise<Array<bookmarks.FlatNode>>;

export function Undo():Promise<bookmarks.HistoryState>;

export function UpdateBookmark(arg1:string,arg2:wailsapi.BookmarkPatchDTO):Promise<void>;

export function UpdateFolderName(arg1:string,arg2:string):Promise<void>;
