// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App is the main application service.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

/**
 * CreateBookmarkFile shows a native save dialog, writes an empty Netscape bookmarks file,
 * and returns the created path.
 * @returns {$CancellablePromise<string>}
 */
export function CreateBookmarkFile() {
    return $Call.ByID(4240421791);
}

/**
 * GetFilePath returns the file path passed via CLI arg.
 * @returns {$CancellablePromise<string>}
 */
export function GetFilePath() {
    return $Call.ByID(653068122);
}

/**
 * LoadBookmarkFile loads the bookmark file into the handler and returns any error.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function LoadBookmarkFile(path) {
    return $Call.ByID(2136574459, path);
}

/**
 * OpenFilePicker shows a native file picker dialog and returns the selected path.
 * @returns {$CancellablePromise<string>}
 */
export function OpenFilePicker() {
    return $Call.ByID(3804603101);
}

/**
 * OpenImportFilePicker shows a native file picker dialog for import/merge.
 * @returns {$CancellablePromise<string>}
 */
export function OpenImportFilePicker() {
    return $Call.ByID(1353169140);
}
