// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateBookmarkFile() {
  return window['go']['main']['App']['CreateBookmarkFile']();
}

export function GetFilePath() {
  return window['go']['main']['App']['GetFilePath']();
}

export function LoadBookmarkFile(arg1) {
  return window['go']['main']['App']['LoadBookmarkFile'](arg1);
}

export function OpenFilePicker() {
  return window['go']['main']['App']['OpenFilePicker']();
}
