// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetFilePath():Promise<string>;

export function LoadBookmarkFile(arg1:string):Promise<void>;

export function OpenFilePicker():Promise<string>;
