// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * Handler exposes bookmark operations to the Wails frontend.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bookmarks$0 from "../bookmarks/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddBookmark adds a bookmark to a folder, auto-saves, and returns the created node.
 * Uses AddCommand for lightweight undo (no full-tree snapshot clone).
 * @param {string} parentID
 * @param {$models.BookmarkCreateDTO} bm
 * @returns {$CancellablePromise<bookmarks$0.FlatNode>}
 */
export function AddBookmark(parentID, bm) {
    return $Call.ByID(2540108014, parentID, bm).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * AddFolder adds a folder, auto-saves, and returns the created node.
 * Uses AddCommand for lightweight undo (no full-tree snapshot clone).
 * @param {string} parentID
 * @param {string} name
 * @returns {$CancellablePromise<bookmarks$0.FlatNode>}
 */
export function AddFolder(parentID, name) {
    return $Call.ByID(1167638310, parentID, name).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType0($result);
    }));
}

/**
 * ApplyImportMerge loads another bookmark file, merges additive changes, and saves once.
 * @param {string} path
 * @returns {$CancellablePromise<bookmarks$0.MergeApplyResult>}
 */
export function ApplyImportMerge(path) {
    return $Call.ByID(1698922552, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * DeleteNode deletes a node and auto-saves.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNode(id) {
    return $Call.ByID(896383004, id);
}

/**
 * DeleteNodes deletes multiple nodes and auto-saves once.
 * @param {string[]} ids
 * @returns {$CancellablePromise<void>}
 */
export function DeleteNodes(ids) {
    return $Call.ByID(2327402173, ids);
}

/**
 * FetchFavicon fetches a favicon for a URL by preferring the page's declared icon,
 * then falling back to /favicon.ico, then finally to Google's favicon service.
 * @param {string} pageURL
 * @returns {$CancellablePromise<string>}
 */
export function FetchFavicon(pageURL) {
    return $Call.ByID(1441610639, pageURL);
}

/**
 * FetchFaviconsForNodes refreshes bookmark favicons, saves once at the end,
 * and returns the updated nodes for targeted frontend patching.
 * Uses UpdateBookmarkCommand for lightweight undo (no full-tree snapshot clone).
 * @param {string[]} ids
 * @returns {$CancellablePromise<bookmarks$0.FlatNode[]>}
 */
export function FetchFaviconsForNodes(ids) {
    return $Call.ByID(2200483544, ids).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * FetchPageTitle fetches the <title> from a URL.
 * @param {string} pageURL
 * @returns {$CancellablePromise<string>}
 */
export function FetchPageTitle(pageURL) {
    return $Call.ByID(558166856, pageURL);
}

/**
 * FilePath returns the currently loaded file path.
 * @returns {$CancellablePromise<string>}
 */
export function FilePath() {
    return $Call.ByID(3206040014);
}

/**
 * GetAllFolders returns all folder nodes in the tree (for move target selection).
 * @returns {$CancellablePromise<$models.NodeDTO[]>}
 */
export function GetAllFolders() {
    return $Call.ByID(507762033).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType4($result);
    }));
}

/**
 * GetFlatIndex returns a flat index of all bookmarks for search.
 * @returns {$CancellablePromise<bookmarks$0.BookmarkIndexEntry[]>}
 */
export function GetFlatIndex() {
    return $Call.ByID(775586902).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType6($result);
    }));
}

/**
 * GetFlatTree returns the current bookmark tree as a flat list of nodes.
 * Each node has a parentId reference instead of nested children.
 * @returns {$CancellablePromise<bookmarks$0.FlatNode[]>}
 */
export function GetFlatTree() {
    return $Call.ByID(862529726).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetFolderChildren returns the direct children of a folder as flat DTOs.
 * Used for lazy loading -- fetches a folder's contents on demand.
 * @param {string} folderID
 * @returns {$CancellablePromise<bookmarks$0.FlatNode[]>}
 */
export function GetFolderChildren(folderID) {
    return $Call.ByID(292694722, folderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetHistoryState returns whether undo/redo is currently available.
 * @returns {$CancellablePromise<bookmarks$0.HistoryState>}
 */
export function GetHistoryState() {
    return $Call.ByID(1775200136).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * GetRootNodes returns only the root-level nodes as flat DTOs.
 * Used for lazy loading -- initial load only sends the top level.
 * @returns {$CancellablePromise<bookmarks$0.FlatNode[]>}
 */
export function GetRootNodes() {
    return $Call.ByID(3478698114).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType2($result);
    }));
}

/**
 * GetTreeStats returns the total number of folders and bookmarks in the tree.
 * @returns {$CancellablePromise<$models.TreeStats>}
 */
export function GetTreeStats() {
    return $Call.ByID(2519800388).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType8($result);
    }));
}

/**
 * LoadFile loads a Netscape bookmark HTML file and parses it into the tree.
 * @param {string} path
 * @returns {$CancellablePromise<void>}
 */
export function LoadFile(path) {
    return $Call.ByID(3118286381, path);
}

/**
 * MoveNode moves a node, auto-saves, and returns metadata for targeted frontend patching.
 * Uses MoveCommand for lightweight undo (no full-tree snapshot clone).
 * @param {string} nodeID
 * @param {string} newParentID
 * @param {number} newIndex
 * @returns {$CancellablePromise<$models.MoveResult>}
 */
export function MoveNode(nodeID, newParentID, newIndex) {
    return $Call.ByID(509824950, nodeID, newParentID, newIndex).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * MoveNodes moves multiple nodes, auto-saves once, and returns metadata for targeted frontend patching.
 * Uses MultiMoveCommand for lightweight undo (no full-tree snapshot clone).
 * @param {string[]} nodeIDs
 * @param {string} targetFolderID
 * @returns {$CancellablePromise<$models.MoveResult>}
 */
export function MoveNodes(nodeIDs, targetFolderID) {
    return $Call.ByID(2606142239, nodeIDs, targetFolderID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * OpenURL opens a URL in the default browser.
 * @param {string} pageURL
 * @returns {$CancellablePromise<void>}
 */
export function OpenURL(pageURL) {
    return $Call.ByID(1491583384, pageURL);
}

/**
 * PreviewImportMerge loads another bookmark file and reports what would be merged.
 * @param {string} path
 * @returns {$CancellablePromise<bookmarks$0.MergePreview>}
 */
export function PreviewImportMerge(path) {
    return $Call.ByID(103580344, path).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * Redo reapplies the most recently undone command.
 * @returns {$CancellablePromise<bookmarks$0.HistoryState>}
 */
export function Redo() {
    return $Call.ByID(284923655).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * Undo reverts the last undoable command.
 * @returns {$CancellablePromise<bookmarks$0.HistoryState>}
 */
export function Undo() {
    return $Call.ByID(38447277).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * UpdateBookmark updates a bookmark and auto-saves.
 * Uses UpdateBookmarkCommand for lightweight undo (no full-tree snapshot clone).
 * @param {string} id
 * @param {$models.BookmarkPatchDTO} patch
 * @returns {$CancellablePromise<void>}
 */
export function UpdateBookmark(id, patch) {
    return $Call.ByID(1256554274, id, patch);
}

/**
 * UpdateFolderName renames a folder and auto-saves.
 * Uses UpdateFolderNameCommand for lightweight undo (no full-tree snapshot clone).
 * @param {string} id
 * @param {string} name
 * @returns {$CancellablePromise<void>}
 */
export function UpdateFolderName(id, name) {
    return $Call.ByID(3196948193, id, name);
}

// Private type creation functions
const $$createType0 = bookmarks$0.FlatNode.createFrom;
const $$createType1 = bookmarks$0.MergeApplyResult.createFrom;
const $$createType2 = $Create.Array($$createType0);
const $$createType3 = $models.NodeDTO.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = bookmarks$0.BookmarkIndexEntry.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = bookmarks$0.HistoryState.createFrom;
const $$createType8 = $models.TreeStats.createFrom;
const $$createType9 = $models.MoveResult.createFrom;
const $$createType10 = bookmarks$0.MergePreview.createFrom;
