// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as bookmarks$0 from "../bookmarks/models.js";

export class BookmarkCreateDTO {
    /**
     * Creates a new BookmarkCreateDTO instance.
     * @param {Partial<BookmarkCreateDTO>} [$$source = {}] - The source object to create the BookmarkCreateDTO.
     */
    constructor($$source = {}) {
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("iconURI" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconURI"] = "";
        }
        if (!("meta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["meta"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkCreateDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BookmarkCreateDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BookmarkCreateDTO(/** @type {Partial<BookmarkCreateDTO>} */($$parsedSource));
    }
}

export class BookmarkDTO {
    /**
     * Creates a new BookmarkDTO instance.
     * @param {Partial<BookmarkDTO>} [$$source = {}] - The source object to create the BookmarkDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("url" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["url"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("iconURI" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["iconURI"] = "";
        }
        if (!("addDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["addDate"] = "";
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastModified"] = "";
        }
        if (!("meta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["meta"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BookmarkDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BookmarkDTO(/** @type {Partial<BookmarkDTO>} */($$parsedSource));
    }
}

export class BookmarkPatchDTO {
    /**
     * Creates a new BookmarkPatchDTO instance.
     * @param {Partial<BookmarkPatchDTO>} [$$source = {}] - The source object to create the BookmarkPatchDTO.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["title"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["url"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["icon"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["iconURI"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | null | undefined}
             */
            this["meta"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new BookmarkPatchDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {BookmarkPatchDTO}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new BookmarkPatchDTO(/** @type {Partial<BookmarkPatchDTO>} */($$parsedSource));
    }
}

export class FolderDTO {
    /**
     * Creates a new FolderDTO instance.
     * @param {Partial<FolderDTO>} [$$source = {}] - The source object to create the FolderDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("icon" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["icon"] = "";
        }
        if (!("addDate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["addDate"] = "";
        }
        if (!("lastModified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["lastModified"] = "";
        }
        if (!("meta" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["meta"] = "";
        }
        if (!("children" in $$source)) {
            /**
             * @member
             * @type {NodeDTO[]}
             */
            this["children"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FolderDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FolderDTO}
     */
    static createFrom($$source = {}) {
        const $$createField6_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("children" in $$parsedSource) {
            $$parsedSource["children"] = $$createField6_0($$parsedSource["children"]);
        }
        return new FolderDTO(/** @type {Partial<FolderDTO>} */($$parsedSource));
    }
}

export class MoveResult {
    /**
     * Creates a new MoveResult instance.
     * @param {Partial<MoveResult>} [$$source = {}] - The source object to create the MoveResult.
     */
    constructor($$source = {}) {
        if (!("movedNodes" in $$source)) {
            /**
             * @member
             * @type {bookmarks$0.FlatNode[]}
             */
            this["movedNodes"] = [];
        }
        if (!("oldParentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["oldParentId"] = "";
        }
        if (!("newParentId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["newParentId"] = "";
        }
        if (!("newIndex" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["newIndex"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MoveResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MoveResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType3;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("movedNodes" in $$parsedSource) {
            $$parsedSource["movedNodes"] = $$createField0_0($$parsedSource["movedNodes"]);
        }
        return new MoveResult(/** @type {Partial<MoveResult>} */($$parsedSource));
    }
}

export class NodeDTO {
    /**
     * Creates a new NodeDTO instance.
     * @param {Partial<NodeDTO>} [$$source = {}] - The source object to create the NodeDTO.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {bookmarks$0.NodeType}
             */
            this["type"] = bookmarks$0.NodeType.$zero;
        }
        if (!("folder" in $$source)) {
            /**
             * @member
             * @type {FolderDTO | null}
             */
            this["folder"] = null;
        }
        if (!("bookmark" in $$source)) {
            /**
             * @member
             * @type {BookmarkDTO | null}
             */
            this["bookmark"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new NodeDTO instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {NodeDTO}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType5;
        const $$createField3_0 = $$createType7;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("folder" in $$parsedSource) {
            $$parsedSource["folder"] = $$createField2_0($$parsedSource["folder"]);
        }
        if ("bookmark" in $$parsedSource) {
            $$parsedSource["bookmark"] = $$createField3_0($$parsedSource["bookmark"]);
        }
        return new NodeDTO(/** @type {Partial<NodeDTO>} */($$parsedSource));
    }
}

/**
 * TreeStats holds aggregate counts for the bookmark tree.
 */
export class TreeStats {
    /**
     * Creates a new TreeStats instance.
     * @param {Partial<TreeStats>} [$$source = {}] - The source object to create the TreeStats.
     */
    constructor($$source = {}) {
        if (!("folders" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["folders"] = 0;
        }
        if (!("bookmarks" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["bookmarks"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TreeStats instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TreeStats}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TreeStats(/** @type {Partial<TreeStats>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = NodeDTO.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = bookmarks$0.FlatNode.createFrom;
const $$createType3 = $Create.Array($$createType2);
const $$createType4 = FolderDTO.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = BookmarkDTO.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
